on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 17
      - name: Install dependencies
        run: npm ci
      - name: Run integration tests
        run: npm run test
    env:
      JWT_SECRET: ${{secrets.JWT_SECRET}}
  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3
      - name: Build and Deploy API
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "caderneta-online-back"
          heroku_email: "rafaelaugustscherer@gmail.com"
          usedocker: true
          stack: container
          appdir: "back-end"
    env:
      HD_JWT_SECRET: ${{secrets.JWT_SECRET}}
      HD_DB_CONNECTION_URI: ${{secrets.DB_CONNECTION_URI}}
